# Site settings
title: Dan Magnusson
email: pastadiablo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Dan Magnusson, veteran software development engineer.  
  Specialist focusing on native iOS development, and C# game development (Godot, Unity).
  Here you can find information on him, his resume, his projects, his socials, and his thoughts about development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pastadiablo.com" # the base hostname & protocol for your site
twitter_username: pastadiablo
github_username:  pastadiablo

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

collections_dir: collections/
collections:
  blog:
    output: true
    permalink: /blog/:title/
  projects:
    output: true
    permalink: /projects/:title/