# Site settings
title: Dan Magnusson
email: pastadiablo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Dan Magnusson, software & game developer.  
  A generalist programmer, Dan likes to work on games, play games, and watch other people play games.  
  He seems to have a sort of obsession with games.  
  Here you can find info on games he's worked on, and his thoughts about games and games development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pastadiablo.com" # the base hostname & protocol for your site
twitter_username: pastadiablo
github_username:  pastadiablo

# Build settings
markdown: kramdown
